// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dimytljytbktauxdkmbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpbXl0bGp5dGJrdGF1eGRrbWJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODEwMDYsImV4cCI6MjA2NTU1NzAwNn0.jpikSh3Ajy_FzlgqCTrWSUuBrOZggS8_qpRMCIz44PA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);